"""Manage `.gheasy/config.json`, generate GitHub Actions workflows, and run `gh_*` CI/CD helpers."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% ../nbs/00_core.ipynb #82502491347e4ae5
from __future__ import annotations
import re, subprocess as sp, stat, os, yaml
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any
from ghapi.all import GhApi
from fastcore.all import store_attr, patch, filter_values, true, Path, filter_keys, in_, L, listify, not_, is_
from .workflow import Workflow, JobBuilder, StepBuilder

# %% auto #0
__all__ = ['FINDING_BRANCH_PROTECTION', 'FINDING_DEPENDABOT', 'FINDING_TOPICS', 'FINDING_LFS', 'FINDING_HOOKS', 'FINDING_BUILD',
           'FINDING_WORKFLOWS', 'app', 'EnvConfig', 'DeployOptions', 'GheasyConfig', 'cfg_path', 'mk_deploy_job',
           'mk_workflow', 'mk_gitattributes', 'mk_dependabot', 'mk_hook', 'nbdev_hook', 'gh_hooks',
           'gh_githooks_pre_commit', 'gh_lfs', 'gh_gitattributes', 'gh_protect', 'gh_topics', 'gh_secret',
           'gh_push_env', 'gh_secrets_from_file', 'gh_deploy_key_setup', 'gh_init', 'gh_add_env', 'gh_add_job',
           'gh_workflow', 'gh_status', 'gh_ship', 'gh_record_deploy', 'gh_setup', 'RepoFinding', 'gh_check', 'gh_apply',
           'GheasyRepo', 'gh_pyproject_to_hatchling', 'main']

# %% ../nbs/00_core.ipynb #11v4pz14mo9k
@dataclass
class EnvConfig:
    host: str
    domain: str
    branch: str = 'main'
    srv_path: str = '/srv/app'

@dataclass
class DeployOptions:
    user: str = 'deploy'
    key: str = None
    build: bool = True
    exclude: list = field(default_factory=list)
    extra_dirs: list = field(default_factory=list)
    health_timeout: int = 60

@dataclass
class GheasyConfig:
    """Mutable config backed by `.gheasy/config.json`.
    Chainable mutating methods return `self` for fluent use.
    Use `GheasyConfig.load(path)` to read; `.save(path)` to write.
    Not thread-safe: do not share instances across concurrent callers."""
    app: str = ''
    envs: dict = field(default_factory=dict)           # {env_name: EnvConfig}
    health_path: str = '/health'
    test_cmd: str = None
    env_schema: dict = field(default_factory=dict)     # {KEY: None} → secret, {KEY: "val"} → variable
    hooks: dict = field(default_factory=dict)
    lfs: list = field(default_factory=list)
    workflows: dict = field(default_factory=dict)      # opt-in flags, all False by default
    workflow_preset: str = None                        # 'python'|'fasthtml'|'fastapi-react'|'nodejs'|'rust'|'go'
    deploy_cmd: str = None                             # override deploy step; None = skip deploy job
    extra_jobs: dict = field(default_factory=dict)
    deploys: dict = field(default_factory=dict)        # runtime state, persisted but not in workflow YAML
    deploy_pkg: str = None

@patch
def add_env(self:GheasyConfig, name, host, domain, branch=None, srv_path='/srv/app'):
    self.envs[name] = EnvConfig(host=host, domain=domain, branch=branch or 'main', srv_path=srv_path)
    return self

@patch
def set_lfs(self:GheasyConfig, patterns):
    self.lfs = list(patterns)
    return self

@patch
def set_hooks(self:GheasyConfig, hooks):
    self.hooks = hooks
    return self

@patch
def set_workflows(self:GheasyConfig, workflows):
    self.workflows = {**self.workflows, **workflows}
    return self

@patch
def add_job(self:GheasyConfig, name, job):
    self.extra_jobs[name] = job
    return self

@patch
def to_dict(self:GheasyConfig): return asdict(self)

@patch(cls_method=True)
def from_dict(cls:GheasyConfig, d):
    envs = {k: EnvConfig(**v) for k, v in d.get('envs', {}).items()}
    rest = filter_keys(d, lambda k: k in cls.__dataclass_fields__ and k != 'envs')
    return cls(envs=envs, **rest)

@patch
def save(self:GheasyConfig, path='.'):
    cfg_path(path).write_json(self.to_dict())
    return self

@patch(cls_method=True)
def load(cls:GheasyConfig, path='.'):
    'Load config from .gheasy/config.json. Raises FileNotFoundError if absent.'
    return cls.from_dict(cfg_path(path).read_json()) if cfg_path(path).exists() else cls()

# %% ../nbs/00_core.ipynb #2b0fcmk3rqu
@patch(cls_method=True)
def from_pyproject(cls:GheasyConfig, path='.'):
    "Bootstrap config from pyproject.toml [project] name."
    import tomllib
    with open(Path(path)/'pyproject.toml', 'rb') as f: data = tomllib.load(f)
    return cls(app=data['project']['name'])

# %% ../nbs/00_core.ipynb #g6c9fitg1g5
def cfg_path(path='.') -> Path:
    'Return path to .gheasy/config.json'
    return Path(path) / '.gheasy' / 'config.json'

# %% ../nbs/00_core.ipynb #4g701qfdat6
_preset = {'python': {}, 'fasthtml': {}, 'rust': {'rust': True}, 'go': {'go': True},
'fastapi-react': {'node': True}, 'nodejs': {'node': True}}

def _res_wfs(cfg):
    "Merge preset defaults with explicit cfg.workflows (explicit always wins)."
    base = _preset.get(cfg.workflow_preset, {}) if cfg.workflow_preset else {}
    return {**base, **cfg.workflows}

def mk_deploy_job(env_name, cfg, wfb, cmd=None):
    "Add deploy job for env_name to wfb using DSL. Returns None (with warning) if no deploy cmd."
    env = cfg.envs[env_name]
    deploy_step = cmd or cfg.deploy_cmd
    if not deploy_step:
        print(f'Warning: no deploy_cmd configured for {env_name!r} — skipping deploy job. '
              f'Set cfg.deploy_cmd or pass cmd= to mk_deploy_job.')
        return None
    (wfb.job(f'deploy-{env_name}').runs_on('ubuntu-latest').needs('test').environment(env_name)
        .if_(f"github.ref == 'refs/heads/{env.branch}'").checkout().end_step()
        .setup_uv().end_step()
        .step('Deploy SSH key').run(
            'mkdir -p ~/.ssh && echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa '
            '&& chmod 600 ~/.ssh/id_rsa\n'
            f'ssh-keyscan {env.host} >> ~/.ssh/known_hosts').end_step()
        .step(f'Deploy to {env_name}').run(deploy_step).end_job())

# %% ../nbs/00_core.ipynb #9bvbw4hr4iw
def _inject_raw_job(job_id, wfb, raw):
    "Convert a raw job dict into a JobBuilder attached to wfb."
    jb, steps = JobBuilder(job_id, wfb), raw.pop('steps', [])
    jb._data.update(raw)
    for sd in steps:
        sb = StepBuilder(sd.get('name', ''), jb)
        sb._data = sd
        jb._steps.append(sb)
    wfb._jobs.append(jb)
    wfb._job_map[job_id] = jb

# %% ../nbs/00_core.ipynb #aehbt6iu5gg
def mk_workflow(cfg, *,
    on_pull_request: bool | None = None,    # also trigger on pull_request events
    test:            bool | None = None,    # uv test job (pytest by default, cfg.test_cmd to override)
    lint:            bool | None = None,    # ruff check + format (needs: test)
    publish_pypi:    bool | None = None,    # PyPI trusted publishing on release (needs: test)
    docker_build:    bool | None = None,    # Docker build + push to GHCR (needs: test)
    node:            bool | None = None,    # Node.js build + test (frontend job)
    rust:            bool | None = None,    # Rust build + test + clippy
    go:              bool | None = None,    # Go build + test + vet
):
    '''Generate complete GitHub Actions workflow YAML from a GheasyConfig.
    Each flag enables a corresponding job. `None` (default) defers to the
    value resolved from `cfg.workflow_preset` + `cfg.workflows`. Passing
    `True` or `False` overrides cfg for that flag.
    Example::
        cfg = GheasyConfig.from_pyproject().add_env('prod', '1.2.3.4', 'myapp.com')
        cfg.deploy_cmd = './deploy.sh'
        print(mk_workflow(cfg, test=True, lint=True))
    '''
    kw = dict(on_pull_request=on_pull_request, test=test, lint=lint, publish_pypi=publish_pypi,
             docker_build=docker_build, node=node, rust=rust, go=go)
    flags = _res_wfs(cfg) | filter_values(kw, not_(is_(None)))
    branches = list({e.branch for e in cfg.envs.values()}) or ['main']
    wfb = Workflow(f'{cfg.app} CI')
    wfb.on.push(branches=branches)
    if flags.get('on_pull_request'): wfb.on.pull_request(branches=branches)
    if flags.get('test'): wfb.uv_test_job(**({'test_cmd': cfg.test_cmd} if cfg.test_cmd else {}))
    if flags.get('lint'): wfb.uv_lint_job()
    if flags.get('publish_pypi'): wfb.uv_pypi_job()
    if flags.get('docker_build'): wfb.docker_job(cfg.app)
    if flags.get('node'): wfb.node_job()
    if flags.get('rust'): wfb.rust_job()
    if flags.get('go'): wfb.go_job()
    for env_name in cfg.envs: mk_deploy_job(env_name, cfg, wfb)
    for name, job in cfg.extra_jobs.items(): _inject_raw_job(name, wfb, dict(job))
    return '# Managed by gheasy — do not edit directly\n' + wfb.build().to_yaml()

# %% ../nbs/00_core.ipynb #hxa3q4g7igs
_lfs_st, _lfs_end = '# BEGIN gheasy-lfs', '# END gheasy-lfs'

def mk_gitattributes(patterns):
    'Generate LFS block for .gitattributes with sentinel comments.'
    st, end = _lfs_st, _lfs_end
    ga = L(patterns).map(lambda p: f'{p} filter=lfs diff=lfs merge=lfs -text')
    return '\n'.join(st+ga+end) + '\n'

def mk_dependabot(ecosystems=('pip', 'github-actions'), schedule='weekly', assignees=None, lbls=None):
    'Generate .github/dependabot.yml content.'
    opt = dict(assignees=listify(assignees)) if assignees else {} | dict(labels=listify(lbls)) if lbls else {}
    def upd(eco): return {'package-ecosystem': eco, 'directory': '/', 'schedule': {'interval': schedule}}|opt
    return yaml.dump(dict(version=2,updates=L(ecosystems).map(upd)), sort_keys=False)

def mk_hook(cmd):
    'Generate a bash hook script with gheasy-managed sentinels.'
    return f'''
    #!/bin/bash
    # BEGIN gheasy-managed
    {cmd}
    # END gheasy-managed
    '''.strip() + '\n'

# %% ../nbs/00_core.ipynb #6u3ybaa27pw
def nbdev_hook():
    "Return the pre-commit cmd that runs nbdev_prepare via uv, injecting nbdev if not in project deps."
    return 'uv run --with nbdev nbdev-prepare'

def gh_hooks(hooks=None, path='.'):
    """Install git hooks. hooks = {'pre-commit': cmd, ...} where cmd is a str or list[str].
    Reads cfg.hooks if hooks not passed."""
    hooks = hooks or GheasyConfig.load(path).hooks
    if not hooks: return
    if not (git_dir := Path(path) / '.git').exists(): print(f'no .git directory at {path!r}.'); return
    hooks_dir = git_dir / 'hooks'
    hooks_dir.mkdir(exist_ok=True)
    for name, cmd in hooks.items():
        if isinstance(cmd, list): cmd = '\n'.join(cmd)
        hp = hooks_dir / name
        ex, block = hp.read_text() if hp.exists() else '', mk_hook(cmd)
        sentinel_re = re.compile(r'# BEGIN gheasy-managed.*?# END gheasy-managed\n', re.DOTALL)
        if sentinel_re.search(ex): nc = sentinel_re.sub(block, ex)
        else: nc = ex + ('\n' if ex and not ex.endswith('\n') else '') + block
        hp.write_text(nc)
        hp.chmod(hp.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

def gh_githooks_pre_commit(cmd=None, path='.'):
    "Install pre-commit hook. Defaults to nbdev_hook(). Pass cmd= to override."
    gh_hooks({'pre-commit': cmd or nbdev_hook()}, path=path)

# %% ../nbs/00_core.ipynb #kxqgeuw616
_LFS_DEFAULTS = ['*.db', '*.onnx', '*.bin', '*.pt', '*.pkl', '*.safetensors', '*.tar.gz', '*.mp4', '*.parquet']

def gh_lfs(patterns=None, persist=True, path='.'):
    "Track LFS patterns. If persist=True, saves to config (source of truth for gh_gitattributes)."
    patterns = patterns or _LFS_DEFAULTS
    sp.run(['git', 'lfs', 'install'], cwd=path, check=True, capture_output=True)
    for p in patterns: sp.run(['git', 'lfs', 'track', p], cwd=path, check=True, capture_output=True)
    if persist: GheasyConfig.load(path).set_lfs(patterns).save(path)

def gh_gitattributes(path='.'):
    """Regenerate gheasy-managed LFS block in .gitattributes from config.
    Preserves all non-managed lines. Call after gh_lfs(persist=True)."""
    if not cfg_path(path).exists(): print('No .gheasy/config.json — run gh_init first.'); return
    cfg = GheasyConfig.load(path)
    if not cfg.lfs: print('No LFS patterns in config — run gh_lfs(persist=True) first.'); return
    ga_path = Path(path) / '.gitattributes'
    existing = ga_path.read_text() if ga_path.exists() else ''
    block = mk_gitattributes(cfg.lfs)
    sentinel_re = re.compile(r'# BEGIN gheasy-lfs.*?# END gheasy-lfs\n', re.DOTALL)
    new_content = sentinel_re.sub(block, existing) if sentinel_re.search(existing) else existing + block
    ga_path.write_text(new_content)

# %% ../nbs/00_core.ipynb #f10q8efcizt
def _resolve_gh_token(token=None):
    "Tiered resolution: explicit > GITHUB_TOKEN env"
    return token or os.getenv('GITHUB_TOKEN')

def _get_repo_slug(path='.'):
    "Parse (owner, repo) from git remote URL."
    r = sp.run(['git', 'remote', 'get-url', 'origin'], cwd=path, capture_output=True, text=True)
    url = r.stdout.strip()
    m = re.search(r'[:/]([^/]+)/([^/]+?)(?:\.git)?$', url)
    if not m: raise ValueError(f'Cannot parse owner/repo from remote: {url}')
    return m.group(1), m.group(2)

def _gh_api(token=None, path='.'):
    "Return (owner, repo_name, GhApi) instance."
    owner, repo = _get_repo_slug(path)
    return owner, repo, GhApi(owner=owner, repo=repo, token=token)

def gh_protect(branch='main', require_reviews=1, dismiss_stale=True, require_status_checks=('test',),
           enforce_admins=False, allow_force_pushes=False, token=None, path='.'):
    "Set branch protection rules via ghapi. Requires token with repo admin scope."
    owner, repo, api = _gh_api(token or _resolve_gh_token(), path)
    rsc = dict(strict=True, contexts=listify(require_status_checks))
    rprr=dict(required_approving_review_count=require_reviews, dismiss_stale_reviews=dismiss_stale)
    api.repos.update_branch_protection(branch=branch, enforce_admins=enforce_admins, required_status_checks=rsc,
        required_pull_request_reviews=rprr, restrictions=None, allow_force_pushes=allow_force_pushes)

def gh_topics(topics, token=None, path='.'):
    "Replace repo topics. GitHub enforces lowercase."
    owner, repo, api = _gh_api(_resolve_gh_token(token), path)
    api.repos.replace_all_topics(names=[t.lower() for t in topics])

# %% ../nbs/00_core.ipynb #s8wmfzkskm
def gh_secret(key, value, env=None, dry_run=False):
    "Set a single GitHub secret, optionally scoped to an environment."
    cmd = ['gh', 'secret', 'set', key, '--body', value]
    if env: cmd += ['--env', env]
    if dry_run: print(f'[dry-run] {" ".join(cmd)}'); return
    sp.run(cmd, check=True)

def gh_push_env(envs, dry_run=False, path='.'):
    """Route env vars to secrets or variables using cfg.env_schema.
    Schema: {KEY: None} -> Secret, {KEY: 'default'} -> Variable."""
    if not cfg_path(path).exists(): raise FileNotFoundError('No .gheasy/config.json')
    cfg = GheasyConfig.load(path)
    schema = cfg.env_schema
    for k in filter_keys(envs, not_(in_(schema))): print(f'Warning: {k} not in env_schema, skipping')
    for k,v in filter_keys(envs, in_(schema)).items():
         if schema[k] is None: gh_secret(k, v, dry_run=dry_run)
         else:
             cmd = ['gh', 'variable', 'set', k, '--body', v]
             if dry_run: print(f'[dry-run] {" ".join(cmd)}')
             else: sp.run(cmd, check=True)

def gh_secrets_from_file(env_file='.env', env=None, dry_run=False):
    "Read KEY=VALUE pairs from env_file and push all as GitHub secrets."
    lines = Path(env_file).read_text().splitlines()
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#'): continue
        key, _, value = line.partition('=')
        gh_secret(key.strip(), value.strip(), env=env, dry_run=dry_run)

# %% ../nbs/00_core.ipynb #crwye8a19w
def gh_deploy_key_setup(key_path, dry_run=False):
    """Read SSH private key from file and push as DEPLOY_KEY GitHub secret.

    Step 3 of deploy key setup (steps 1-2 require manual SSH access):
    1. Generate key pair: ssh-keygen -t ed25519 -f deploy_key
    2. Add public key to server ~/.ssh/authorized_keys (manual)
    3. Call this function with the private key path to upload to GitHub secrets
    """
    key = Path(key_path).read_text()
    gh_secret('DEPLOY_KEY', key, dry_run=dry_run)
    if not dry_run: print(f'DEPLOY_KEY set from {key_path}')

# %% ../nbs/00_core.ipynb #09i3wyq774kl
def _git_branch(path='.'):
    "Detect current git branch, defaulting to 'main'."
    r = sp.run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], cwd=path, capture_output=True, text=True)
    return r.stdout.strip() or 'main'

def _resolve_gh_repo_input(ref=None, path='.'):
    "Normalize to (owner, repo). Accepts 'owner/repo', GitHub URL, or local path."
    if ref is None: return _get_repo_slug(path)
    if '/' in ref and 'github.com' not in ref: return tuple(ref.split('/', 1))
    m = re.search(r'github\.com[:/]([^/]+)/([^/]+?)(?:\.git)?$', ref)
    if m: return m.group(1), m.group(2)
    raise ValueError(f'Cannot parse owner/repo from: {ref}')

# %% ../nbs/00_core.ipynb #ib1pn67pbvb
def gh_init(name, host, domain, env='prod', branch=None, srv_path='/srv/app',
            health_path='/health', test_cmd=None, env_schema=None,
            hooks=None, lfs=None, workflows=None, workflow_preset=None,
            deploy_cmd=None, path='.'):
    "Create or update .gheasy/config.json."
    branch = branch or _git_branch(path)
    cfg = GheasyConfig(app=name, health_path=health_path, test_cmd=test_cmd, env_schema=env_schema or {},
        hooks=hooks or {}, lfs=lfs or [], workflows=workflows or {}, workflow_preset=workflow_preset,deploy_cmd=deploy_cmd)
    cfg.add_env(env, host, domain, branch=branch, srv_path=srv_path)
    cfg.save(path)
    print(f'Config written to {cfg_path(path)}')
    return cfg_path(path)

# %% ../nbs/00_core.ipynb #x01zud50gef
def gh_add_env(env, host, domain, branch=None, srv_path='/srv/app', path='.'):
    "Add or update an environment in config. Regenerates workflow locally."
    cfg = GheasyConfig.load(path)
    cfg.add_env(env, host, domain, branch=branch or _git_branch(path), srv_path=srv_path)
    cfg.save(path)
    wf_path = Path(path) / '.github' / 'workflows' / 'gheasy.yml'
    wf_path.parent.mkdir(parents=True, exist_ok=True)
    wf_path.write_text(mk_workflow(cfg))
    print(f'Added env {env!r}. Run gh_workflow() to push to GitHub.')

def gh_add_job(name, job, path='.'):
    "Add a custom GitHub Actions job dict to config. Run gh_workflow() to push."
    cfg = GheasyConfig.load(path)
    cfg.add_job(name, job).save(path)
    print(f'Added job {name!r}. Run gh_workflow() to push.')

def gh_workflow(token=None, path='.'):
    "Write workflow YAML locally. With token, also uploads via ghapi."
    cfg = GheasyConfig.load(path)
    wf_str = mk_workflow(cfg)
    wf_path = Path(path) / '.github' / 'workflows' / 'gheasy.yml'
    wf_path.parent.mkdir(parents=True, exist_ok=True)
    wf_path.write_text(wf_str)
    print(f'Workflow written to {wf_path}')
    if token:
        import base64
        owner, repo, api = _gh_api(token, path)
        content = base64.b64encode(wf_str.encode()).decode()
        try:
            existing = api.repos.get_content(path='.github/workflows/gheasy.yml')
            api.repos.create_or_update_file_contents(
                path='.github/workflows/gheasy.yml',
                message='chore: update gheasy workflow',
                content=content, sha=existing.sha)
        except Exception:
            api.repos.create_or_update_file_contents(
                path='.github/workflows/gheasy.yml',
                message='chore: add gheasy workflow',
                content=content)
        print('Workflow uploaded to GitHub.')

def gh_status(path='.'):
    "Print deploy state table."
    if not cfg_path(path).exists():
        print('No .gheasy/config.json found.')
        return
    cfg = GheasyConfig.load(path)
    if not cfg.deploys:
        print('No deploys recorded yet.')
        return
    print(f'{"Env":<12} {"Domain":<30} {"Version":<10} {"Deployed At":<25} {"Status"}')
    print('-' * 90)
    for env_name, d in cfg.deploys.items():
        env_cfg = cfg.envs.get(env_name, EnvConfig(host='?', domain='?'))
        print(f'{env_name:<12} {env_cfg.domain:<30} {d.get("version","?")[:8]:<10} '
              f'{d.get("deployed_at","?"):<25} {d.get("status","?")}')

def gh_ship(token=None, path='.'):
    "Push workflow YAML (optionally to GitHub API) then print status."
    gh_workflow(token=token, path=path)
    gh_status(path=path)

def gh_record_deploy(env, sha, path='.'):
    "Record deploy state to config. Called by CI after successful deploy."
    cfg = GheasyConfig.load(path)
    cfg.deploys[env] = {
        'version': sha,
        'deployed_at': datetime.now(timezone.utc).isoformat(),
        'status': 'active',
    }
    cfg.save(path)

# %% ../nbs/00_core.ipynb #6xg1jrjs84s
def gh_setup(name, host, domain, env='prod', branch=None, srv_path='/srv/app',
             test_cmd=None, env_schema=None, token=None,
             hooks=None, hook_cmd='uv run nbdev_prepare',
             lfs=None, workflows=None, workflow_preset=None,
             deploy_cmd=None, path='.'):
    """One-call setup: gh_init + gh_workflow + gh_hooks.
    Set hooks={} to skip hook installation."""
    gh_init(name, host, domain, env=env, branch=branch, srv_path=srv_path,
            health_path='/health', test_cmd=test_cmd, env_schema=env_schema,
            hooks=hooks or {}, lfs=lfs, workflows=workflows,
            workflow_preset=workflow_preset, deploy_cmd=deploy_cmd, path=path)
    gh_workflow(token=token, path=path)
    if hooks is None: gh_hooks({'pre-commit': hook_cmd}, path=path)
    elif hooks: gh_hooks(hooks, path=path)
    return cfg_path(path)

# %% ../nbs/00_core.ipynb #dynqnblcxs
FINDING_BRANCH_PROTECTION = 'branch-protection'
FINDING_DEPENDABOT        = 'dependabot'
FINDING_TOPICS            = 'topics'
FINDING_LFS               = 'lfs'
FINDING_HOOKS             = 'hooks'
FINDING_BUILD             = 'build'
FINDING_WORKFLOWS         = 'workflows'

@dataclass
class RepoFinding:
    "A single finding from a repo health check."
    level: str      # 'ok' | 'warn' | 'error'
    category: str
    message: str
    fix: Any = None
    cmd_repr: str = ''
    docs: str = ''

    def __repr__(self):
        icon = {'ok': '\u2713', 'warn': '\u26a0', 'error': '\u2717'}.get(self.level, '?')
        hint = f' \u2192 {self.cmd_repr}' if self.cmd_repr else ''
        return f'{icon} [{self.category}] {self.message}{hint}'

    def apply(self):
        if self.fix: self.fix()
        else: print(f'No auto-fix for {self.category}: {self.cmd_repr}')

# %% ../nbs/00_core.ipynb #a76qogw8a3i
def gh_check(owner=None, repo=None, token=None, path='.', remote=True, local=True, verbose=True):
    "Audit repo health. local: hooks/gitattributes/pyproject. remote: protection/topics/dependabot."
    chks = []
    if local:
        hp = Path(path) / '.git' / 'hooks' / 'pre-commit'
        if hp.exists() and 'gheasy-managed' in hp.read_text():
            chks.append(RepoFinding('ok', FINDING_HOOKS, 'pre-commit hook installed'))
        else: chks.append(RepoFinding('warn', FINDING_HOOKS, 'No gheasy pre-commit hook',
              fix=lambda: gh_githooks_pre_commit(path=path), cmd_repr='gh_githooks_pre_commit()'))

        ga = Path(path) / '.gitattributes'
        if ga.exists() and '# BEGIN gheasy-lfs' in ga.read_text():
            chks.append(RepoFinding('ok', FINDING_LFS, '.gitattributes has LFS block'))
        else: chks.append(RepoFinding('warn', FINDING_LFS, 'No gheasy LFS block in .gitattributes',
            fix=lambda: gh_gitattributes(path=path), cmd_repr='gh_gitattributes()'))

        pp = Path(path) / 'pyproject.toml'
        if pp.exists():
            if 'hatchling' in pp.read_text():
	            chks.append(RepoFinding('ok', FINDING_BUILD, 'pyproject.toml uses hatchling'))
            else: chks.append(RepoFinding('warn', FINDING_BUILD, 'pyproject.toml not using hatchling',
                fix=lambda: gh_pyproject_to_hatchling(path=path), cmd_repr='gh_pyproject_to_hatchling()'))

    if remote and (token or _resolve_gh_token()):
        try:
            if owner is None or repo is None: owner, repo = _get_repo_slug(path)
            api = GhApi(owner=owner, repo=repo, token=token or _resolve_gh_token())
            repo_data = api.repos.get()
            if repo_data.topics: chks.append(RepoFinding('ok', FINDING_TOPICS, f'Topics set: {repo_data.topics}'))
            else: chks.append(RepoFinding('warn', FINDING_TOPICS, 'No topics set', cmd_repr='gh_topics([...])'))
            try:
                api.repos.get_content(path='.github/dependabot.yml')
                chks.append(RepoFinding('ok', FINDING_DEPENDABOT, 'dependabot.yml exists'))
            except: chks.append(RepoFinding('warn', FINDING_DEPENDABOT, 'No dependabot.yml',
                                                cmd_repr='write .github/dependabot.yml'))
        except Exception as e: chks.append(RepoFinding('warn', FINDING_BRANCH_PROTECTION, f'Could not check remote: {e}'))

    if verbose: L(chks).map(print)
    return chks

def gh_apply(findings, dry_run=False, confirm=False):
    "Auto-fix all non-ok findings that have a fix callable."
    applied = []
    for f in findings:
        if f.level == 'ok' or f.fix is None: continue
        if dry_run: print(f'[dry-run] would fix: {f.category} \u2192 {f.cmd_repr}'); continue
        if confirm:
            resp = input(f'Fix {f.category}? ({f.cmd_repr}) [y/N] ')
            if resp.lower() != 'y': continue
        f.apply()
        applied.append(f)
    return applied

# %% ../nbs/00_core.ipynb #tdl70w5uvjp
@dataclass
class GheasyRepo:
    "Thin stateful shell over gh_* functions. All logic lives in standalone functions."
    ref: str = None
    token: str = None
    path: str = '.'

    def __post_init__(self):
        if self.ref: self._owner, self._repo = _resolve_gh_repo_input(self.ref, self.path)
        else: self._owner, self._repo = None, None

    @property
    def full_name(self): return f'{self._owner}/{self._repo}' if self._owner and self._repo else None

    def check(self, remote=True, local=True, verbose=True):
        return gh_check(self._owner, self._repo, self.token, self.path, remote, local, verbose)

    def apply(self, findings=None, dry_run=False, confirm=False):
        if findings is None: findings = self.check(verbose=False)
        return gh_apply(findings, dry_run=dry_run, confirm=confirm)

    def create(self, private=True, description='', auto_init=False):
        api = GhApi(token=self.token or _resolve_gh_token())
        return api.repos.create_for_authenticated_user(
            name=self._repo, private=private,
            description=description, auto_init=auto_init)

    @classmethod
    def new(cls, ref, template='nbdev', private=True, description='',
            token=None, parent_dir='.', topics=None, workflows=None):
        "Full project scaffold: create repo, clone, configure, push."
        owner, repo = _resolve_gh_repo_input(ref)
        inst = cls(ref=ref, token=token or _resolve_gh_token())
        inst.create(private=private, description=description)
        sp.run(['git', 'clone', f'https://github.com/{owner}/{repo}', str(Path(parent_dir) / repo)], check=True)
        local_path = Path(parent_dir) / repo
        if template == 'nbdev': sp.run(['uv', 'run', 'nbdev-new'], cwd=local_path, check=True)
        gh_pyproject_to_hatchling(path=local_path)
        gh_lfs(persist=True, path=local_path)
        gh_githooks_pre_commit(path=local_path)
        if workflows: gh_init(repo, '', '', workflows=workflows, path=local_path)
        gh_workflow(token=inst.token, path=local_path)
        sp.run(['git', 'add', '-A'], cwd=local_path, check=True)
        sp.run(['git', 'commit', '-m', 'chore: gheasy init'], cwd=local_path, check=True)
        sp.run(['git', 'push', '-u', 'origin', 'HEAD'], cwd=local_path, check=True)
        if topics: gh_topics(topics, token=inst.token, path=local_path)
        return cls(ref=ref, token=inst.token, path=str(local_path))

# %% ../nbs/00_core.ipynb #o7xzaged6f9
def _migrate_pyproject_to_hatchling(path='.'):
    "Convert pyproject.toml to hatchling. Returns True if changes made."
    import tomlkit
    pp = Path(path) / 'pyproject.toml'
    if not pp.exists(): return False
    doc = tomlkit.parse(pp.read_text())
    changed = False
    bs = doc.setdefault('build-system', {})
    if bs.get('build-backend') != 'hatchling.build':
        bs['build-backend'] = 'hatchling.build'
        bs['requires'] = ['hatchling']
        changed = True
    name = doc.get('project', {}).get('name', '')
    if name:
        targets = doc.setdefault('tool', {}).setdefault('hatch', {}).setdefault('build', {}).setdefault('targets', {})
        wheel = targets.setdefault('wheel', {})
        if wheel.get('packages') != [name]:
            wheel['packages'] = [name]
            changed = True
        sdist = targets.setdefault('sdist', {})
        sdist_includes = [f'/{name}', '/README.md', '/pyproject.toml']
        if sdist.get('include') != sdist_includes:
            sdist['include'] = sdist_includes
            changed = True
    for key in ('setuptools', 'setup-tools'):
        if key in doc.get('tool', {}):
            del doc['tool'][key]
            changed = True
    if changed: pp.write_text(tomlkit.dumps(doc))
    return changed

def gh_pyproject_to_hatchling(path='.', dry_run=False):
    "Convert pyproject.toml to hatchling build backend. Idempotent."
    if dry_run:
        print(f'[dry-run] Would migrate {Path(path) / "pyproject.toml"} to hatchling')
        return
    changed = _migrate_pyproject_to_hatchling(path)
    print('Migrated to hatchling.' if changed else 'Already using hatchling (no changes).')

# %% ../nbs/00_core.ipynb #iemfvar26t
from cyclopts import App as _App

app = _App(name='gheasy', help='GitHub made easy \u2014 git workflows, CI/CD, hooks, LFS.')

app.command(gh_setup)
app.command(gh_init)
app.command(gh_add_env)
app.command(gh_add_job)
app.command(gh_workflow)
app.command(gh_ship)
app.command(gh_status)
app.command(gh_check)
app.command(gh_apply)
app.command(gh_hooks)
app.command(gh_lfs)
app.command(gh_gitattributes)
app.command(gh_protect)
app.command(gh_topics)
app.command(gh_push_env)
app.command(gh_secrets_from_file)
app.command(gh_pyproject_to_hatchling)

def main(): app()
