"""Every repository a workspace can see, listed in one stable order, with one operation across all of them.

Docs: https://vedicreader.github.io/gheasy/repos.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_repos.ipynb.

# %% ../nbs/03_repos.ipynb #34468103
from __future__ import annotations

import hashlib, json, os, re, shutil, subprocess
from collections import Counter
from dataclasses import dataclass

from fastcore.all import Path, first, patch
from fastcore.parallel import parallel
from fastcore.xdg import xdg_config_home

from .repo import GitError, GitRepo, repo_root, url_name
from .repo import clone as git_clone

# %% auto #0
__all__ = ['MEMBERS', 'OPS', 'WORKERS', 'STATE_DIR', 'clone_url', 'discover', 'RepoSet', 'repo_for', 'find_repos']

# %% ../nbs/03_repos.ipynb #9871ce58
MEMBERS = 'repos.txt'                            #: one repository per line, `#` starts a comment
OPS = ('fetch', 'pull', 'push', 'status')
WORKERS = 8
STATE_DIR = xdg_config_home()/'gheasy'/'repos'   #: where a `RepoSet` remembers what was added or hidden

def _members_file(root):
    "The entries of the `repos.txt` beside an open folder."
    try: text = (Path(root)/MEMBERS).read_text(encoding='utf-8', errors='replace')
    except OSError: return []
    lines = (line.split('#', 1)[0].strip() for line in text.splitlines())
    return [line for line in lines if line]

def _member_root(entry, folder):
    "The local worktree a `repos.txt` line names, or None if it is not checked out here."
    entry = str(entry).strip()
    if not entry: return None
    if entry.startswith(('http://', 'https://', 'git@', 'ssh://', 'git://')):
        candidate = Path(folder)/url_name(entry)
    else:
        candidate = Path(entry).expanduser()
        if not candidate.is_absolute(): candidate = Path(folder)/candidate
        if not candidate.is_dir() and '/' in entry:
            candidate = Path(folder)/entry.rstrip('/').rpartition('/')[2]
    return repo_root(candidate) if candidate.is_dir() else None

def clone_url(spec):
    "`owner/name` is the shorthand a list is written with; anything else is already a URL."
    spec = str(spec or '').strip()
    return f'https://github.com/{spec}.git' if re.fullmatch(r'[\w.-]+/[\w.-]+', spec) else spec

# %% ../nbs/03_repos.ipynb #58cc4fd0
def discover(roots, extra=(), hidden=()):
    "Repository roots for a workspace of folders, in a stable, explainable order."
    out, seen = [], set()
    def take(path):
        if path is None or str(path) in seen: return
        seen.add(str(path))
        out.append(Path(path))
    for folder in roots:
        folder = Path(folder).expanduser().resolve()
        take(repo_root(folder))
        try:
            children = sorted((c for c in folder.iterdir() if c.is_dir() and not c.name.startswith('.')),
                key=lambda c: c.name.lower())
        except OSError:
            children = []
        for child in children:
            if (child/'.git').exists(): take(child)
        for entry in _members_file(folder): take(_member_root(entry, folder))
    for path in extra: take(repo_root(Path(path).expanduser()))
    away = {str(Path(h)) for h in hidden}
    return [p for p in out if str(p) not in away]

# %% ../nbs/03_repos.ipynb #17f12604
@dataclass
class RepoSet:
    "The repositories a workspace lists, and the operations that mean something across all of them."
    roots: list
    store: Path = None                       #: defaults to a file under `STATE_DIR`, named after the roots
    def __post_init__(self):
        self.roots = [Path(r).expanduser().resolve() for r in self.roots]
        key = hashlib.sha256('\0'.join(map(str, self.roots)).encode()).hexdigest()[:16]
        self.store = Path(self.store) if self.store else STATE_DIR/f'{key}.json'

@patch
def _state(self:RepoSet):
    try: return json.loads(self.store.read_text(encoding='utf-8')) or {}
    except (OSError, ValueError): return {}

@patch
def _save(self:RepoSet, state):
    self.store.parent.mkdir(parents=True, exist_ok=True)
    self.store.write_text(json.dumps(state, indent=1), encoding='utf-8')

@patch
def paths(self:RepoSet):
    "Every repository this workspace lists."
    state = self._state()
    return discover(self.roots, state.get('extra') or (), state.get('hidden') or ())

@patch
def require(self:RepoSet, path):
    "The repository a caller named, refused unless this workspace already lists it."
    want = str(Path(str(path)).expanduser().resolve())
    found = first(p for p in self.paths() if str(p) == want)
    if found is None: raise GitError(f'{path} is not a repository in this workspace')
    return found

@patch
def add(self:RepoSet, path):
    "List a repository this workspace would not have found, and un-hide one it removed."
    root = repo_root(Path(str(path)).expanduser())
    if root is None: raise GitError(f'{path} is not inside a Git repository')
    state = self._state()
    state['hidden'] = [h for h in (state.get('hidden') or []) if h != str(root)]
    extra = state.get('extra') or []
    if str(root) not in extra and root not in discover(self.roots): extra += [str(root)]
    state['extra'] = extra
    self._save(state)
    return root

@patch
def remove(self:RepoSet, path):
    "Drop a repository from the list. A discovered one is hidden; nothing is deleted."
    root = self.require(path)
    state = self._state()
    state['extra'] = [e for e in (state.get('extra') or []) if e != str(root)]
    if root in discover(self.roots, state['extra']):
        state['hidden'] = sorted({*(state.get('hidden') or []), str(root)})
    self._save(state)
    return root

# %% ../nbs/03_repos.ipynb #8888fa55
def _fan(items, work):
    "Run `work` over every item at once. Git is a subprocess, so this is IO, not compute."
    items = list(items)
    return list(parallel(work, items, n_workers=min(WORKERS, len(items)), threadpool=True))

@patch
def overview(self:RepoSet, expect=''):
    "Every repository as one row, plus what the workspace looks like as a whole."
    def brief(path):
        try:
            return GitRepo(path).brief()
        except (GitError, OSError) as e:
            return {'root': str(path), 'name': Path(path).name, 'error': str(e),
                'branch': '', 'clean': True, 'changed': 0, 'ahead': 0, 'behind': 0,
                'unreleased': None}
    rows = _fan(self.paths(), brief)
    named = [r['branch'] for r in rows if r.get('branch') and not r.get('error')]
    expected = str(expect or '').strip() or (Counter(named).most_common(1)[0][0] if named else '')
    for row in rows:
        row['off_branch'] = bool(expected) and not row.get('error') and row['branch'] != expected
    return {
        'repos': rows, 'expected_branch': expected, 'roots': [str(r) for r in self.roots],
        'summary': {
            'repos': len(rows),
            'dirty': sum(1 for r in rows if not r.get('clean')),
            'ahead': sum(1 for r in rows if r.get('ahead')),
            'behind': sum(1 for r in rows if r.get('behind')),
            'off_branch': sum(1 for r in rows if r.get('off_branch')),
            'unreleased': sum(1 for r in rows if r.get('unreleased')),
            'errors': sum(1 for r in rows if r.get('error')),
        },
    }

# %% ../nbs/03_repos.ipynb #15791d37
@patch
def run(self:RepoSet, op, paths=()):
    "One operation across the named repositories, or across all of them."
    if op not in OPS: raise GitError(f'unknown workspace operation: {op}')
    targets = [self.require(p) for p in paths] if paths else self.paths()
    def act(path):
        row = {'root': str(path), 'name': Path(path).name, 'ok': True, 'skipped': '', 'output': ''}
        try:
            repo = GitRepo(path)
            if op == 'status': return row
            if op == 'fetch': return row | {'output': repo.fetch() or 'up to date'}
            if op == 'pull':
                repo.fetch()
                state = repo.brief(fresh=True)
                if not state['upstream']: return row | {'skipped': 'no upstream'}
                if not state['behind']: return row | {'skipped': 'already current'}
                return row | {'output': repo.pull()['summary']}
            state = repo.brief(fresh=True)
            if not state['upstream']: return row | {'skipped': 'unpublished branch'}
            if not state['ahead']: return row | {'skipped': 'nothing to push'}
            return row | {'output': repo.push() or 'pushed'}
        except (GitError, OSError) as e:
            return row | {'ok': False, 'error': str(e)}
    return _fan(targets, act)

# %% ../nbs/03_repos.ipynb #077db265
@patch
def clone(self:RepoSet, urls, into=None):
    "Clone repositories into an open folder, in parallel, and say where each landed."
    parent = Path(str(into)).expanduser().resolve() if into else (self.roots[0] if self.roots else None)
    if parent is None: raise GitError('open a folder to clone into')
    if not any(parent == r or parent.is_relative_to(r) for r in self.roots):
        raise GitError(f'{parent} is outside the open folders')
    specs = [s for s in (str(u).strip() for u in (urls or ())) if s]
    if not specs: raise GitError('give at least one repository to clone')
    def act(spec):
        row = {'spec': spec, 'ok': True, 'skipped': '', 'output': ''}
        try:
            return row | {'root': str(git_clone(clone_url(spec), parent)), 'output': 'cloned'}
        except (GitError, OSError) as e:
            return row | {'ok': False, 'error': str(e)}
    return _fan(specs, act)

# %% ../nbs/03_repos.ipynb #eea0a888
def repo_for(roots, target='', chosen=None, cwd=None, store=None):
    "The repository a view is about: one this workspace lists, the chosen folder's, or the open file's."
    roots = [Path(r).expanduser().resolve() for r in roots]
    if str(target or '').strip(): return RepoSet(roots, store).require(target)
    if chosen is not None:
        chosen = Path(chosen).expanduser().resolve()
        if chosen in roots and (root := repo_root(chosen)) is not None: return root
    if cwd is None: raise GitError('open a folder first')
    return repo_root(cwd) or Path(cwd)

# %% ../nbs/03_repos.ipynb #ed2b36c2
def find_repos(base, query='', limit=60, depth=6):
    "Repositories anywhere under `base`, for picking one out of a directory of checkouts."
    base = Path(base or '').expanduser()
    if not base.is_dir(): return []
    q, out, seen = str(query or '').strip().lower(), [], set()
    def take(repo):
        key = str(repo)
        rel = os.path.relpath(key, base).lower()   # relative to `base`: an ancestor's name is not a match
        if key in seen or (q and q not in repo.name.lower() and q not in rel): return
        seen.add(key)
        out.append(repo)
    exe = shutil.which('rg')
    if exe:
        # `--max-depth` counts files, and a repository's marker is `<repo>/.git/HEAD`, two below it.
        cmd = [exe, '--files', '--hidden', '--no-ignore', '--no-messages',
            '--max-depth', str(int(depth) + 2), '-g', '**/.git/HEAD', '-g', '**/.git',
            *[g for d in ('.git/objects', '.git/logs', 'node_modules', '.venv', 'venv',
                '.cache', 'Library', '.Trash', 'site-packages', '__pycache__')
                for g in ('-g', f'!**/{d}')],
            str(base)]
        try:
            p = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
            for line in (p.stdout or '').splitlines():
                hit = Path(line)
                repo = hit.parent.parent if hit.name == 'HEAD' else hit.parent
                if repo.is_dir(): take(repo)
        except (OSError, subprocess.SubprocessError):
            exe = None
    if not exe:
        for cur, dirs, _ in os.walk(base):
            here = Path(cur)
            if len(here.relative_to(base).parts) > depth:
                dirs[:] = []
                continue
            if (here/'.git'/'HEAD').is_file() or (here/'.git').is_file():
                take(here)
                dirs[:] = []
                continue
            dirs[:] = [d for d in dirs if not d.startswith('.') and d not in {'node_modules', '__pycache__'}]
    out.sort(key=lambda p: (p.name.lower(), str(p)))
    return out[:max(1, int(limit))]
