"""Fluent, stateful Python DSL for building and dispatching GitHub Actions workflows."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_workflow.ipynb.

# %% auto #0
__all__ = ['WorkflowNode', 'StepBuilder', 'StrategyBuilder', 'JobBuilder', 'TriggerBuilder', 'WorkflowBuilder', 'WorkflowDoc',
           'Workflow', 'docker_build_push', 'pages_deploy', 'uv_ci']

# %% ../nbs/01_workflow.ipynb #d4e5f6a7
import os, subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from fastcore.basics import filter_values, patch
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq

# %% ../nbs/01_workflow.ipynb #f6a7b8c9
def _yaml_instance() -> YAML:
    y = YAML()
    y.default_flow_style = y.best_map_flow_style =  False
    y.indent(mapping=2, sequence=4, offset=2)
    y.width = 120
    return y

def _hyphenate(**kw) -> dict: return {k.replace("_", "-"): v for k, v in kw.items()}

def _to_yaml_val(v: Any) -> Any:
    'Recursively convert Python dicts/lists to CommentedMap/CommentedSeq.'
    if isinstance(v, dict): return CommentedMap(**{k: _to_yaml_val(val) for k, val in v.items()})
    if isinstance(v, list): return CommentedSeq([_to_yaml_val(i) for i in v])
    return v

def _fv(d:dict) -> dict|None:
    "filter_values shorthand: drop None values, return None if all dropped."
    return filter_values(d, lambda v: v is not None) or None

# %% ../nbs/01_workflow.ipynb #workflownode_cls
class WorkflowNode:
    "Base class providing `job()` and `build()` navigation to all fluent builders."
    @property
    def _wfb(self): return self._workflow
    def job(self, job_id:str, needs=None): return self._wfb.job(job_id, needs=needs)
    def build(self): return self._wfb.build()

# %% ../nbs/01_workflow.ipynb #b8c9d0e1
class StepBuilder(WorkflowNode):
    'Fluent builder for a single workflow step.'
    def __init__(self, name:str, job): self._job, self._data = job, {"name": name}
    @property
    def _wfb(self): return self._job._workflow

# %% ../nbs/01_workflow.ipynb #0b3od12k9gom
@patch
def uses(self:StepBuilder, action:str) -> StepBuilder:
	self._data["uses"] = action
	return self

@patch
def run(self:StepBuilder, cmd:str) -> StepBuilder:
	self._data["run"] = cmd
	return self

@patch
def with_(self:StepBuilder, **kwargs) -> StepBuilder:
    "Map keyword args → `with` block (underscores become hyphens)."
    self._data.setdefault("with", {}).update(_hyphenate(**kwargs))
    return self

@patch
def env(self:StepBuilder, **kwargs) -> StepBuilder:
    self._data.setdefault("env", {}); self._data["env"].update(kwargs)
    return self

@patch
def id(self:StepBuilder, step_id:str) -> StepBuilder:
    self._data["id"] = step_id
    return self

@patch
def if_(self:StepBuilder, condition:str) -> StepBuilder:
    self._data["if"] = condition
    return self

@patch
def continue_on_error(self:StepBuilder, value:bool=True) -> StepBuilder:
    self._data["continue-on-error"] = value
    return self

@patch
def timeout_minutes(self:StepBuilder, minutes:int) -> StepBuilder:
    self._data["timeout-minutes"] = minutes
    return self

@patch
def working_directory(self:StepBuilder, path:str) -> StepBuilder:
    self._data["working-directory"] = path
    return self


# %% ../nbs/01_workflow.ipynb #yx61jj5w7fd
@patch
def checkout(self:StepBuilder, ref:str|None=None, fetch_depth:int|None=None) -> StepBuilder:
    self._data["uses"] = "actions/checkout@v4"
    if ref or fetch_depth is not None:
        self._data.setdefault("with", {})
        if ref: self._data["with"]["ref"] = ref
        if fetch_depth is not None: self._data["with"]["fetch-depth"] = fetch_depth
    return self

@patch
def setup_python(self:StepBuilder, version:str="3.12", cache:str="pip") -> StepBuilder:
    self._data["uses"] = "actions/setup-python@v5"
    self._data["with"] = {"python-version": version}
    if cache: self._data["with"]["cache"] = cache
    return self

@patch
def setup_node(self:StepBuilder, version:str="20", cache:str="npm") -> StepBuilder:
    self._data["uses"] = "actions/setup-node@v4"
    self._data["with"] = {"node-version": version}
    if cache: self._data["with"]["cache"] = cache
    return self

@patch
def cache(self:StepBuilder, path:str, key:str, restore_keys:list[str]|None=None) -> StepBuilder:
    self._data["uses"] = "actions/cache@v4"
    self._data["with"] = {"path": path, "key": key}
    if restore_keys: self._data["with"]["restore-keys"] = "\n".join(restore_keys)
    return self

@patch
def upload_artifact(self:StepBuilder, name:str, path:str, retention_days:int|None=None) -> StepBuilder:
    self._data["uses"] = "actions/upload-artifact@v4"
    self._data["with"] = {"name": name, "path": path}
    if retention_days: self._data["with"]["retention-days"] = retention_days
    return self

@patch
def download_artifact(self:StepBuilder, name:str, path:str|None=None) -> StepBuilder:
    self._data["uses"] = "actions/download-artifact@v4"
    self._data["with"] = {"name": name}
    if path: self._data["with"]["path"] = path
    return self

@patch
def docker_build_push(self:StepBuilder, context:str=".", tags=None, push:bool=False, platforms:str|None=None) -> StepBuilder:
    w = {"context": context, "push": push}
    if tags: w["tags"] = "\n".join(tags) if isinstance(tags, list) else tags
    if platforms: w["platforms"] = platforms
    self._data["uses"] = "docker/build-push-action@v5"
    self._data["with"] = w
    return self

# %% ../nbs/01_workflow.ipynb #mcq1r908nj
@patch
def step(self:StepBuilder, name:str) -> StepBuilder:
    "Add another step to the same job."
    return self._job.step(name)

@patch
def end_step(self:StepBuilder):
    "Return to JobBuilder to continue configuring this job."
    return self._job

@patch
def end_job(self:StepBuilder):
    "Return to WorkflowBuilder, ending this job."
    return self._job._workflow

@patch
def _render(self:StepBuilder) -> CommentedMap: return _to_yaml_val(self._data)

# %% ../nbs/01_workflow.ipynb #e1f2a3b4
@dataclass
class StrategyBuilder:
    "Fluent builder for a job strategy/matrix block."
    _job: Any
    _matrix: dict[str, list[Any]] = field(default_factory=dict)
    _fail_fast: bool | None = None
    _max_parallel: int | None = None
    _include: list[dict] = field(default_factory=list)
    _exclude: list[dict] = field(default_factory=list)

    def matrix(self, **kwargs) -> "StrategyBuilder":
        self._matrix.update(_hyphenate(**kwargs))
        return self

    def include(self, **kwargs) -> "StrategyBuilder":
        self._include.append(kwargs)
        return self

    def exclude(self, **kwargs) -> "StrategyBuilder":
        self._exclude.append(kwargs)
        return self

    def fail_fast(self, value:bool=True) -> "StrategyBuilder":
        self._fail_fast = value
        return self

    def max_parallel(self, n:int) -> "StrategyBuilder":
        self._max_parallel = n
        return self

    def end_strategy(self) -> "JobBuilder":
	    return self._job

    def step(self, name:str) -> StepBuilder: return self._job.step(name)

    def _render(self) -> CommentedMap | None:
        if not self._matrix and self._fail_fast is None: return None
        m = CommentedMap()
        if self._fail_fast is not None: m["fail-fast"] = self._fail_fast
        if self._max_parallel is not None: m["max-parallel"] = self._max_parallel
        if self._matrix:
            mat = _to_yaml_val(self._matrix)
            if self._include: mat["include"] = _to_yaml_val(self._include)
            if self._exclude: mat["exclude"] = _to_yaml_val(self._exclude)
            m["matrix"] = mat
        return m

# %% ../nbs/01_workflow.ipynb #b4c5d6e7
class JobBuilder(WorkflowNode):
    "Fluent builder for a single workflow job."
    def __init__(self, job_id:str, workflow):
        self._id, self._workflow = job_id, workflow
        self._data:dict[str,Any] = {}
        self._steps:list[StepBuilder] = []
        self._strategy = None

# %% ../nbs/01_workflow.ipynb #7sxpkfhkqaf
@patch
def runs_on(self:JobBuilder, runner:str|list[str]) -> JobBuilder:
    self._data["runs-on"] = runner
    return self

@patch
def needs(self:JobBuilder, *job_ids:str) -> JobBuilder:
    self._data["needs"] = list(job_ids) if len(job_ids) > 1 else job_ids[0]
    return self

@patch
def if_(self:JobBuilder, condition:str) -> JobBuilder:
    self._data["if"] = condition
    return self

@patch
def timeout_minutes(self:JobBuilder, minutes:int) -> JobBuilder:
    self._data["timeout-minutes"] = minutes
    return self

@patch
def continue_on_error(self:JobBuilder, value:bool=True) -> JobBuilder:
    self._data["continue-on-error"] = value
    return self

@patch
def env(self:JobBuilder, **kwargs) -> JobBuilder:
    self._data.setdefault("env", {}); self._data["env"].update(kwargs)
    return self

@patch
def permissions(self:JobBuilder, **kwargs) -> JobBuilder:
    self._data["permissions"] = _hyphenate(**kwargs)
    return self

@patch
def outputs(self:JobBuilder, **kwargs) -> JobBuilder:
    "Define job outputs: outputs(artifact_name='${{ steps.upload.outputs.artifact-id }}')"
    self._data["outputs"] = _hyphenate(**kwargs)
    return self

@patch
def concurrency(self:JobBuilder, group:str, cancel_in_progress:bool=True) -> JobBuilder:
    self._data["concurrency"] = {"group": group, "cancel-in-progress": cancel_in_progress}
    return self

@patch
def services(self:JobBuilder, **service_defs) -> JobBuilder:
    self._data["services"] = service_defs
    return self

@patch
def container(self:JobBuilder, image:str, **options) -> JobBuilder:
    self._data["container"] = {"image": image, **options}
    return self

@patch
def environment(self:JobBuilder, name:str) -> JobBuilder:
    "Set the GitHub environment for this job."
    self._data["environment"] = name
    return self

# %% ../nbs/01_workflow.ipynb #jndpnuhf6r9
@patch
def strategy(self:JobBuilder) -> StrategyBuilder:
    self._strategy = StrategyBuilder(_job=self)
    return self._strategy

@patch
def step(self:JobBuilder, name:str) -> StepBuilder:
    s = StepBuilder(name, self); self._steps.append(s)
    return s

@patch
def checkout(self:JobBuilder, ref:str|None=None, fetch_depth:int|None=None) -> StepBuilder:
    return self.step("Checkout").checkout(ref=ref, fetch_depth=fetch_depth)

@patch
def setup_python(self:JobBuilder, version:str="3.12", cache:str="pip") -> StepBuilder:
    return self.step(f"Setup Python {version}").setup_python(version=version, cache=cache)

@patch
def setup_node(self:JobBuilder, version:str="20", cache:str="npm") -> StepBuilder:
    return self.step(f"Setup Node {version}").setup_node(version=version, cache=cache)

@patch
def install(self:JobBuilder, cmd:str="pip install -e '.[dev]'") -> StepBuilder:
    return self.step("Install dependencies").run(cmd)

@patch
def run_tests(self:JobBuilder, cmd:str="pytest") -> StepBuilder:
    return self.step("Run tests").run(cmd)

@patch
def setup_uv(self:JobBuilder, version:str|None=None) -> StepBuilder:
    "Add astral-sh/setup-uv step. Optionally pin a version."
    s = self.step('Setup uv').uses('astral-sh/setup-uv@v5')
    if version: s.with_(version=version)
    return s

@patch
def uv_install(self:JobBuilder, cmd:str='uv sync --frozen') -> StepBuilder:
    "Add a uv dependency install step."
    return self.step('Install dependencies').run(cmd)

@patch
def uv_run(self:JobBuilder, cmd:str) -> StepBuilder:
    "Add a step that runs a command via uv run."
    return self.step(cmd.split()[0].capitalize()).run(f'uv run {cmd}')

# %% ../nbs/01_workflow.ipynb #qms9k2p5gvi
@patch
def end_job(self:JobBuilder): return self._workflow

@patch
def _render(self:JobBuilder) -> CommentedMap:
    m = _to_yaml_val(self._data)
    if self._strategy:
        rendered = self._strategy._render()
        if rendered: m["strategy"] = rendered
    if self._steps:
        m["steps"] = CommentedSeq(s._render() for s in self._steps)
    return m

# %% ../nbs/01_workflow.ipynb #d6e7f8a9
class TriggerBuilder(WorkflowNode):
    "Fluent builder for workflow triggers (`on:` block)."
    def __init__(self, workflow):
        self._workflow, self._triggers = workflow, {}

    @property
    def on(self):
        "Allow `.on.push().on.pull_request()` chaining style."
        return self

    @property
    def done(self):
        "Return to WorkflowBuilder after chaining trigger events."
        return self._workflow

# %% ../nbs/01_workflow.ipynb #q540tiibsk
@patch
def push(self:TriggerBuilder, branches=None, tags=None, paths=None,
         branches_ignore=None, paths_ignore=None) -> TriggerBuilder:
    self._triggers["push"] = _fv({"branches": branches, "tags": tags, "paths": paths,
                                   "branches-ignore": branches_ignore, "paths-ignore": paths_ignore})
    return self

@patch
def pull_request(self:TriggerBuilder, branches=None, types=None, paths=None) -> TriggerBuilder:
    self._triggers["pull_request"] = _fv({"branches": branches, "types": types, "paths": paths})
    return self

@patch
def pull_request_target(self:TriggerBuilder, branches=None, types=None) -> TriggerBuilder:
    self._triggers["pull_request_target"] = _fv({"branches": branches, "types": types})
    return self

# %% ../nbs/01_workflow.ipynb #90y4n95qyco
@patch
def schedule(self:TriggerBuilder, cron:str) -> TriggerBuilder:
    self._triggers.setdefault("schedule", []).append({"cron": cron}); return self

@patch
def workflow_dispatch(self:TriggerBuilder, inputs:dict|None=None) -> TriggerBuilder:
    self._triggers["workflow_dispatch"] = _fv({"inputs": inputs})
    return self

@patch
def workflow_call(self:TriggerBuilder, inputs:dict|None=None, secrets:dict|None=None) -> TriggerBuilder:
    self._triggers["workflow_call"] = _fv({"inputs": inputs, "secrets": secrets})
    return self

# %% ../nbs/01_workflow.ipynb #wx232j40kg
@patch
def release(self:TriggerBuilder, types=None) -> TriggerBuilder:
    self._triggers["release"] = _fv({"types": types})
    return self

@patch
def issues(self:TriggerBuilder, types=None) -> TriggerBuilder:
    self._triggers["issues"] = _fv({"types": types})
    return self

@patch
def issue_comment(self:TriggerBuilder, types=None) -> TriggerBuilder:
    self._triggers["issue_comment"] = _fv({"types": types})
    return self

@patch
def registry_package(self:TriggerBuilder, types=None) -> TriggerBuilder:
    self._triggers["registry_package"] = _fv({"types": types})
    return self

@patch
def create(self:TriggerBuilder) -> TriggerBuilder:
    self._triggers["create"] = None; return self

@patch
def delete(self:TriggerBuilder) -> TriggerBuilder:
    self._triggers["delete"] = None; return self

@patch
def fork(self:TriggerBuilder) -> TriggerBuilder:
    self._triggers["fork"] = None; return self

@patch
def page_build(self:TriggerBuilder) -> TriggerBuilder:
    self._triggers["page_build"] = None; return self

# %% ../nbs/01_workflow.ipynb #hr4kndagtnk
@patch
def _render(self:TriggerBuilder) -> CommentedMap | list | str:
    if not self._triggers: return CommentedMap()
    k = self._triggers.keys()
    is_none = all(v is None for v in self._triggers.values())
    if is_none and len(k) == 1: return next(iter(k))
    return CommentedMap(**{k:_to_yaml_val(self._triggers[k]) for k in self._triggers})

# %% ../nbs/01_workflow.ipynb #a9b0c1d2
class WorkflowBuilder:
    "Top-level fluent workflow builder. Entry point for the DSL."
    def __init__(self, name:str):
        self._name = name
        self._run_name:str|None = None
        self._permissions:dict[str,str]|None = None
        self._env:dict[str,str] = {}
        self._concurrency:dict|None = None
        self._jobs:list[JobBuilder] = []
        self._job_map:dict[str,JobBuilder] = {}
        self.on = TriggerBuilder(self)

# %% ../nbs/01_workflow.ipynb #gcdmhwk82jh
@patch
def run_name(self:WorkflowBuilder, template:str) -> WorkflowBuilder:
    "Set dynamic run name, e.g. '${{ github.actor }} triggered ${{ github.event_name }}'"
    self._run_name = template
    return self

@patch
def permissions(self:WorkflowBuilder, **kwargs) -> WorkflowBuilder:
    "Set workflow-level permissions. Use read/write/none as values."
    self._permissions = _hyphenate(**kwargs)
    return self

@patch
def env(self:WorkflowBuilder, **kwargs) -> WorkflowBuilder:
    self._env.update(kwargs)
    return self

@patch
def concurrency(self:WorkflowBuilder, group:str, cancel_in_progress:bool=True) -> WorkflowBuilder:
    self._concurrency = {"group": group, "cancel-in-progress": cancel_in_progress}
    return self

@patch
def job(self:WorkflowBuilder, job_id:str, needs=None) -> JobBuilder:
    jb = JobBuilder(job_id, self)
    if needs: jb._data["needs"] = needs
    self._jobs.append(jb)
    self._job_map[job_id] = jb
    return jb

@patch
def build(self:WorkflowBuilder): return WorkflowDoc(self)

@patch
def _render(self:WorkflowBuilder) -> CommentedMap:
    doc = CommentedMap()
    doc["name"] = self._name
    if self._run_name: doc["run-name"] = self._run_name
    doc["on"] = self.on._render()
    if self._permissions: doc["permissions"] = _to_yaml_val(self._permissions)
    if self._env: doc["env"] = _to_yaml_val(self._env)
    if self._concurrency: doc["concurrency"] = _to_yaml_val(self._concurrency)
    jobs_map = CommentedMap()
    for jb in self._jobs: jobs_map[jb._id] = jb._render()
    doc["jobs"] = jobs_map
    return doc

# %% ../nbs/01_workflow.ipynb #6mqmpq8s3lw
@patch
def uv_test_job(self:WorkflowBuilder, test_cmd:str='pytest', needs=None, python_versions:list[str]|None=None) -> WorkflowBuilder:
    "Add a uv test job: checkout → setup-uv → sync → test. If `python_versions` is given, adds a strategy matrix."
    job = self.job('test', needs=needs).runs_on('ubuntu-latest')
    if python_versions: job.strategy().matrix(python_version=python_versions).end_strategy()
    job.checkout().end_step().setup_uv().end_step().uv_install().step('Test').run(f'uv run {test_cmd}').end_job()
    return self

@patch
def uv_lint_job(self:WorkflowBuilder, lint_cmd:str='uv run ruff check . && uv run ruff format --check .', needs=None) -> WorkflowBuilder:
    "Add a uv lint job: checkout → setup-uv → sync → lint. `lint_cmd` defaults to ruff check+format."
    (self.job('lint', needs=needs).runs_on('ubuntu-latest').checkout().end_step().setup_uv().end_step().uv_install()
     .step('Lint').run(lint_cmd).end_job())
    return self

@patch
def uv_pypi_job(self:WorkflowBuilder, needs='test') -> WorkflowBuilder:
    "Add a PyPI publish job (Trusted Publishing / OIDC) — triggered only on release events."
    (self.job('publish', needs=needs)
        .runs_on('ubuntu-latest')
        .if_("github.event_name == 'release'")
        .permissions(id_token='write')
        .checkout().end_step().setup_uv().end_step()
        .step('Build').run('uv build').end_step()
        .step('Publish').uses('pypa/gh-action-pypi-publish@release/v1').end_job())
    return self

@patch
def docker_job(self:WorkflowBuilder, app_name:str, needs='test') -> WorkflowBuilder:
    """Add a Docker build+push job targeting GHCR with a simple ``latest`` tag.

    This is a quick preset for GHCR deploys. For production workflows with
    semver/sha tags use ``docker_build_push()`` which employs ``metadata-action``.
    """
    (self.job('docker', needs=needs)
        .runs_on('ubuntu-latest')
        .permissions(contents='read', packages='write')
        .checkout().end_step()
        .step('Login to GHCR').uses('docker/login-action@v3').with_(
            registry='ghcr.io',
            username='${{ github.actor }}',
            password='${{ secrets.GITHUB_TOKEN }}').end_step()
        .step('Build and push').uses('docker/build-push-action@v5').with_(
            push=True,
            tags=f'ghcr.io/${{{{ github.repository_owner }}}}/{app_name}:latest').end_job())
    return self

@patch
def node_job(self:WorkflowBuilder) -> WorkflowBuilder:
    "Add a Node.js frontend job: setup-node → npm ci → build → test."
    (self.job('frontend')
        .runs_on('ubuntu-latest')
        .checkout().end_step()
        .step('Setup Node').uses('actions/setup-node@v4').with_(node_version='20').end_step()
        .step('Build and test').run('npm ci && npm run build && npm test').end_job())
    return self

@patch
def rust_job(self:WorkflowBuilder) -> WorkflowBuilder:
    "Add a Rust build+test+clippy job."
    (self.job('build')
        .runs_on('ubuntu-latest')
        .checkout().end_step()
        .step('Rust toolchain').uses('dtolnay/rust-toolchain@stable').end_step()
        .step('Build and test').run('cargo build && cargo test && cargo clippy -- -D warnings').end_job())
    return self

@patch
def go_job(self:WorkflowBuilder) -> WorkflowBuilder:
    "Add a Go build+test+vet job."
    (self.job('build')
        .runs_on('ubuntu-latest')
        .checkout().end_step()
        .step('Setup Go').uses('actions/setup-go@v5').with_(go_version='1.22').end_step()
        .step('Build and test').run('go build ./... && go test ./... && go vet ./...').end_job())
    return self

# %% ../nbs/01_workflow.ipynb #c1d2e3f4
class WorkflowDoc:
    "Immutable, serializable workflow document produced by WorkflowBuilder.build()."
    def __init__(self, builder:WorkflowBuilder):
        self._builder = builder
        self._rendered:CommentedMap = builder._render()

# %% ../nbs/01_workflow.ipynb #kdcvqp17rr
@patch
def to_yaml(self:WorkflowDoc) -> str:
    import io
    buf = io.StringIO()
    _yaml_instance().dump(self._rendered, buf)
    return buf.getvalue()

@patch
def save(self:WorkflowDoc, path:str|Path) -> Path:
    p = Path(path); p.parent.mkdir(parents=True, exist_ok=True)
    with open(p, "w") as f: _yaml_instance().dump(self._rendered, f)
    return p

@patch
def __repr__(self:WorkflowDoc) -> str: return self.to_yaml()

# %% ../nbs/01_workflow.ipynb #ajttu9le0ui
@patch
def dispatch(self:WorkflowDoc, owner:str, repo:str, ref:str="main",
             inputs:dict|None=None, token:str|None=None):
    "Trigger workflow_dispatch via ghapi. Returns the API response."
    from ghapi.all import GhApi
    tok = token or os.environ.get("GITHUB_TOKEN")
    if not tok: raise ValueError("GitHub token required: pass token= or set GITHUB_TOKEN env var")
    api = GhApi(owner=owner, repo=repo, token=tok)
    return api.actions.create_workflow_dispatch(
        workflow_id=f"{self._builder._name}.yml", ref=ref, inputs=inputs or {})

@patch
def upload(self:WorkflowDoc, owner:str, repo:str, branch:str="main",
           token:str|None=None, commit_message:str|None=None):
    "Create or update the workflow YAML file in the repo via the GitHub Contents API."
    import base64
    from ghapi.all import GhApi
    tok = token or os.environ.get("GITHUB_TOKEN")
    if not tok: raise ValueError("GitHub token required: pass token= or set GITHUB_TOKEN env var")
    api = GhApi(owner=owner, repo=repo, token=tok)
    filename = f"{self._builder._name}.yml"
    path = f".github/workflows/{filename}"
    content_b64 = base64.b64encode(self.to_yaml().encode()).decode("ascii")
    msg = commit_message or f"ci: add/update {filename} workflow [ghaflow]"
    sha = None
    try: sha = api.repos.get_content(path=path, ref=branch).sha
    except Exception: pass
    kwargs = dict(path=path, message=msg, content=content_b64, branch=branch)
    if sha: kwargs["sha"] = sha
    return api.repos.create_or_update_file_contents(**kwargs)

@patch
def list_runs(self:WorkflowDoc, owner:str, repo:str, token:str|None=None, per_page:int=10):
    "List recent workflow runs for this workflow."
    from ghapi.all import GhApi
    tok = token or os.environ.get("GITHUB_TOKEN")
    if not tok: raise ValueError("GitHub token required")
    api = GhApi(owner=owner, repo=repo, token=tok)
    return api.actions.list_workflow_runs(
        workflow_id=f"{self._builder._name}.yml", per_page=per_page)

# %% ../nbs/01_workflow.ipynb #gc68z2utr8
@patch
def watch(self:WorkflowDoc, run_id:int, owner:str, repo:str) -> None:
    "Stream live logs via `gh run watch`. Requires gh CLI installed and authenticated."
    subprocess.run(["gh","run","watch",str(run_id),"--repo",f"{owner}/{repo}"], check=True)

@patch
def logs(self:WorkflowDoc, run_id:int, owner:str, repo:str) -> None:
    "Print logs of a completed run via `gh run view --log`."
    subprocess.run(["gh","run","view",str(run_id),"--log","--repo",f"{owner}/{repo}"], check=True)

# %% ../nbs/01_workflow.ipynb #f4a5b6c7
def Workflow(name: str) -> WorkflowBuilder:
    """
    Entry point for the fluent workflow DSL.

    Example:
        wfb = Workflow("ci")
        wfb.on.push(branches=["main"])
        wfb.uv_test_job().uv_lint_job()
        wfb.build().save(".github/workflows/ci.yml")
    """
    return WorkflowBuilder(name)

# %% ../nbs/01_workflow.ipynb #b6c7d8e9
def docker_build_push(
    name: str = "Docker Build & Push",
    registry: str = "ghcr.io",
    image_name: str = "${{ github.repository }}",
    branches: list[str] | None = None,
) -> WorkflowDoc:
    """Build and push a Docker image to GHCR using ``metadata-action`` for production tags.

    Uses ``docker/metadata-action`` to produce semver and commit-sha tags
    automatically. For a quick deploy with a simple ``latest`` tag, use the
    ``docker_job()`` ``WorkflowBuilder`` preset instead.
    """
    br = branches or ["main"]
    wf = Workflow(name)
    wf.on.push(branches=br)
    wf.permissions(contents="read", packages="write")
    (wf.job("build-push").runs_on("ubuntu-latest").checkout()
        .step("Log in to GHCR")
            .uses("docker/login-action@v3")
            .with_(registry=registry, username="${{ github.actor }}", password="${{ secrets.GITHUB_TOKEN }}")
        .step("Extract metadata")
            .id("meta")
            .uses("docker/metadata-action@v5")
            .with_(images=f"{registry}/{image_name}")
        .step("Build and push")
            .docker_build_push(tags="${{ steps.meta.outputs.tags }}", push=True))
    return wf.build()

def pages_deploy(
    name: str = "Deploy to GitHub Pages",
    build_cmd: str = "npm run build",
    artifact_path: str = "dist/",
    node_version: str = "20",
) -> WorkflowDoc:
    """Build a static site and deploy to GitHub Pages."""
    wf = Workflow(name)
    wf.on.push(branches=["main"]).workflow_dispatch()
    wf.permissions(contents="read", pages="write", id_token="write")
    wf.concurrency("pages", cancel_in_progress=True)
    (wf.job("build").runs_on("ubuntu-latest").checkout().setup_node(version=node_version)
        .step("Install").run("npm ci")
        .step("Build").run(build_cmd)
        .step("Upload Pages artifact")
            .uses("actions/upload-pages-artifact@v3")
            .with_(path=artifact_path).end_job())
    (wf.job("deploy", needs="build").runs_on("ubuntu-latest")
        .permissions(pages="write", id_token="write")
        .step("Deploy to GitHub Pages").uses("actions/deploy-pages@v4"))
    return wf.build()

# %% ../nbs/01_workflow.ipynb #jo9srtnowop
def uv_ci(
    name: str = "CI",
    python_versions: list[str] | None = None,
    test_cmd: str| None = "pytest",
    lint_cmd: str | None = "uv run ruff check . && uv run ruff format --check .",
    branches: list[str] | None = None,
) -> WorkflowDoc:
    """Standard Python/uv CI: checkout → setup-uv → sync → lint + test.

    Uses uv for dependency management. Delegates to ``uv_lint_job`` and
    ``uv_test_job`` presets for consistent step layout.

    Args:
        test_cmd: Bare command passed to ``uv run`` (e.g. ``"pytest"`` → ``uv run pytest``).
        lint_cmd: Full lint command. Pass ``None`` to skip the lint job entirely.
            Defaults to ruff check+format via ``uv_lint_job`` preset default.
        python_versions: When set, adds a strategy matrix over Python versions.

    Example::

        doc = uv_ci(name='My CI', python_versions=['3.11', '3.12'])
        doc.save('.github/workflows/ci.yml')
    """
    br = branches or ["main"]
    wfb = Workflow(name)
    wfb.on.push(branches=br).pull_request(branches=br)
    if lint_cmd: wfb.uv_lint_job(lint_cmd=lint_cmd, needs=None)
    wfb.uv_test_job(test_cmd=test_cmd,needs="lint" if lint_cmd else None, python_versions=python_versions)
    return wfb.build()
